export default [
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'build/**',
      'coverage/**',
      '*.log',
      '.DS_Store',
      'src/**/*.js',
      'nodemon.js'
    ]
  },
  {
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly'
      }
    },
    rules: {
      // Posibles errores
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-condition': 'warn',
      'no-control-regex': 'error',
      'no-debugger': 'warn',
      'no-delete-var': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-inner-declarations': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'no-new-symbol': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-octal': 'error',
      'no-prototype-builtins': 'warn',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-undef': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',

      // Mejores prácticas
      'accessor-pairs': 'warn',
      'array-callback-return': 'error',
      'block-scoped-var': 'error',
      'class-methods-use-this': 'off',
      complexity: ['warn', 10],
      'consistent-return': 'error',
      curly: 'error',
      'default-case': 'warn',
      'default-case-last': 'error',
      'default-param-last': 'error',
      'dot-location': ['error', 'property'],
      'dot-notation': 'error',
      eqeqeq: ['error', 'always'],
      'grouped-accessor-pairs': 'error',
      'guard-for-in': 'warn',
      'max-classes-per-file': ['warn', 1],
      'no-alert': 'warn',
      'no-caller': 'error',
      'no-constructor-return': 'error',
      'no-div-regex': 'error',
      'no-else-return': 'error',
      'no-empty-function': 'warn',
      'no-eq-null': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-floating-decimal': 'error',
      'no-global-assign': 'error',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-invalid-this': 'error',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-magic-numbers': 'off',
      'no-multi-spaces': 'error',
      'no-multi-str': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': ['error', { props: false }],
      'no-proto': 'error',
      'no-restricted-properties': 'warn',
      'no-return-assign': 'error',
      'no-return-await': 'error',
      'no-script-url': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unused-expressions': 'error',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-return': 'error',
      'no-void': 'error',
      'no-warning-comments': 'off',
      'prefer-named-capture-group': 'off',
      'prefer-promise-reject-errors': 'warn',
      'prefer-regex-literals': 'warn',
      radix: 'error',
      'require-await': 'error',
      'require-unicode-regexp': 'off',
      'vars-on-top': 'error',
      'wrap-iife': ['error', 'inside'],
      yoda: 'error',

      // Variables
      'init-declarations': 'off',
      'no-label-var': 'error',
      'no-restricted-globals': 'off',
      'no-shadow': ['error', { builtinGlobals: false }],
      'no-shadow-restricted-names': 'error',
      'no-undef-init': 'error',

      // Estilo
      'array-bracket-newline': ['error', 'consistent'],
      'array-bracket-spacing': ['error', 'never'],
      'array-element-newline': 'off',
      'arrow-parens': ['error', 'always'],
      'arrow-spacing': 'error',
      'block-spacing': 'error',
      'brace-style': ['error', '1tbs', { allowSingleLine: true }],
      camelcase: ['error', { properties: 'never' }],
      'capitalized-comments': 'off',
      'comma-dangle': ['error', 'never'],
      'comma-spacing': 'error',
      'comma-style': ['error', 'last'],
      'computed-property-spacing': ['error', 'never'],
      'consistent-this': 'off',
      'eol-last': ['error', 'always'],
      'func-call-spacing': ['error', 'never'],
      'func-name': 'off',
      'func-name-matching': 'off',
      'func-style': 'off',
      'function-call-argument-newline': ['error', 'consistent'],
      'function-paren-newline': ['error', 'consistent'],
      'generator-star-spacing': ['error', 'after'],
      'id-denylist': 'off',
      'id-length': 'off',
      'id-match': 'off',
      'implicit-arrow-linebreak': ['error', 'beside'],
      indent: ['error', 2, { SwitchCase: 1 }],
      'jsx-quotes': 'off',
      'key-spacing': ['error', { beforeColon: false, afterColon: true }],
      'keyword-spacing': 'error',
      'line-comment-position': 'off',
      'linebreak-style': ['error', 'windows'],
      'lines-around-comment': 'off',
      'lines-between-class-members': ['error', 'always'],
      'max-depth': ['warn', 4],
      'max-len': ['warn', { code: 120, tabWidth: 2 }],
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-nested-callbacks': ['warn', 3],
      'max-params': ['warn', 3],
      'max-statements': 'off',
      'max-statements-per-line': ['error', { max: 1 }],
      'multiline-comment-style': 'off',
      'multiline-ternary': 'off',
      'new-cap': 'error',
      'new-parens': 'error',
      'newline-per-chained-call': 'off',
      'no-array-constructor': 'error',
      'no-bitwise': 'off',
      'no-continue': 'off',
      'no-inline-comments': 'off',
      'no-lonely-if': 'error',
      'no-mixed-operators': 'error',
      'no-multi-assign': 'error',
      'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 1 }],
      'no-negated-condition': 'off',
      'no-nested-ternary': 'warn',
      'no-new-object': 'error',
      'no-plusplus': 'off',
      'no-restricted-syntax': 'off',
      'no-spaced-func': 'error',
      'no-tabs': 'error',
      'no-ternary': 'off',
      'no-trailing-spaces': 'error',
      'no-underscore-dangle': 'off',
      'no-unneeded-ternary': 'error',
      'no-whitespace-before-property': 'error',
      'nonblock-statement-body-position': ['error', 'beside'],
      'object-curly-newline': ['error', { consistent: true }],
      'object-curly-spacing': ['error', 'always'],
      'object-property-newline': 'off',
      'one-var': ['error', 'never'],
      'one-var-declaration-per-line': 'error',
      'operator-assignment': 'error',
      'operator-linebreak': ['error', 'before'],
      'padded-blocks': ['error', 'never'],
      'padding-line-between-statements': 'off',
      'prefer-exponentiation-operator': 'error',
      'prefer-object-spread': 'error',
      'quote-props': ['error', 'as-needed'],
      quotes: ['error', 'single', { avoidEscape: true }],
      semi: ['error', 'always'],
      'semi-spacing': 'error',
      'semi-style': ['error', 'last'],
      'sort-keys': 'off',
      'sort-vars': 'off',
      'space-after-keywords': 'off',
      'space-before-blocks': 'error',
      'space-before-function-paren': [
        'error',
        { anonymous: 'never', named: 'never', asyncArrow: 'always' }
      ],
      'space-in-parens': ['error', 'never'],
      'space-infix-ops': 'error',
      'space-return': 'off',
      'space-unary-ops': 'error',
      'spaced-comment': ['error', 'always', { exceptions: ['-', '+'] }],
      'switch-colon-spacing': 'error',
      'template-tag-spacing': ['error', 'never'],
      'unicode-bom': ['error', 'never'],
      'wrap-regex': 'off'
    }
  }
];
